default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: depot_development
  username: saasbook
  password: 

test:
  <<: *default
  database: depot_test
  username: saasbook
  password: 

production:
  <<: *default
  database: depot_production
  username: saasbook
  password: 
